CI: GH workflow test

diff --git a/.github/workflows/aws_efa_validation.yml b/.github/workflows/aws_efa_validation.yml
--- a/.github/workflows/aws_efa_validation.yml
+++ b/.github/workflows/aws_efa_validation.yml
@@ -7,35 +7,55 @@ on:
 jobs:
   run_aws_tests:
     name: Run AWS Tests - ${{ matrix.test_type }}
+    # environment: SWX_AWS
     runs-on: ubuntu-latest
+    env:
+      AWS_DEFAULT_REGION: eu-central-1
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     strategy:
       fail-fast: false
       matrix:
         test_type: [cpp, python]
-    container:
-      image: amazon/aws-cli
-      options: --entrypoint=""
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Install additional tools
+      - name: Check AWS credentials
         run: |
-          yum install -y jq gettext tar gzip git
+          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+            echo "ERROR: AWS credentials are not set."
+            exit 1
+          fi
+
+      - name: Install tools
+        run: |
+          set -exE
+          sudo apt-get -qq update
+          sudo apt-get -qq install -y curl jq gettext tar gzip git unzip
+
+          # Install AWS CLI
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip -qq awscliv2.zip
+          sudo ./aws/install --update
+
+          # Install kubectl
           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
 
       - name: Configure AWS credentials
-        run: |
-          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws configure set region eu-central-1
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-central-1
 
       - name: Run AWS tests
         id: aws_tests
         working-directory: ./contrib/aws-efa
         timeout-minutes: 180
         run: |
+          set -exE
           ./aws_test.sh "${{ matrix.test_type }}" 2>&1 | tee test_output.log
           JOB_ID=$(grep 'JOB_ID=' test_output.log | head -n1 | cut -d= -f2)
           echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
