Move S3 test to faster worker
Signed-off-by: Ovidiu Mara <ovidium@nvidia.com>

diff --git a/.github/workflows/aws_s3_validation.yml b/.github/workflows/aws_s3_validation.yml
--- a/.github/workflows/aws_s3_validation.yml
+++ b/.github/workflows/aws_s3_validation.yml
@@ -17,6 +17,7 @@ jobs:
       AWS_SECRET_ACCESS_KEY: ${{ secrets.NIXL_AWS_SECRET_ACCESS_KEY }}
       AWS_DEFAULT_BUCKET: nixl-ci-test-${{ github.run_id }}
       NIXL_INSTALL_DIR: /opt/nixl
+      KUBECTL_VERSION: v1.35.0
     strategy:
       fail-fast: false
 
@@ -29,8 +30,15 @@ jobs:
       - name: Setup
         run: |
           set -exE
+          sudo apt-get -qq update
+          sudo apt-get -qq install -y curl gettext git gzip jq tar unzip
+
+          # Install kubectl
+          curl --retry 5 --retry-delay 2 --retry-all-errors -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
+          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+
           # Install AWS CLI
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          curl --retry 5 --retry-delay 2 --retry-all-errors "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip -qq awscliv2.zip
           sudo ./aws/install --update
 
@@ -61,19 +69,34 @@ jobs:
           # validate upload file to s3
           echo test > testfile.txt
           aws s3 cp testfile.txt s3://${AWS_DEFAULT_BUCKET}/testfile.txt
-      - name: Build NIXL
-        timeout-minutes: 60
-        run: |
-          ./.gitlab/build.sh $NIXL_INSTALL_DIR $NIXL_INSTALL_DIR -Ddisable_gds_backend=true
+
       - name: Run AWS S3 tests
-        working-directory: ./.gitlab
+        working-directory: ./contrib/aws-efa
         timeout-minutes: 180
+        env:
+          TEST_TIMEOUT: 60
         run: |
-          echo "Running AWS S3 Tests on bucket $AWS_DEFAULT_BUCKET"
-          ./test_plugins.sh ${NIXL_INSTALL_DIR}
+          set -o pipefail
+          
+          # Inject AWS credentials into the pod environment template
+          jq '.podProperties.containers[0].env += [{"name": "AWS_ACCESS_KEY_ID", "value": env.AWS_ACCESS_KEY_ID}, {"name": "AWS_SECRET_ACCESS_KEY", "value": env.AWS_SECRET_ACCESS_KEY}, {"name": "AWS_DEFAULT_BUCKET", "value": env.AWS_DEFAULT_BUCKET}, {"name": "AWS_DEFAULT_REGION", "value": env.AWS_DEFAULT_REGION}]' aws_vars.template > aws_vars_s3.template
+          mv aws_vars_s3.template aws_vars.template
+
+          export BUILD_CMD=".gitlab/build.sh \${NIXL_INSTALL_DIR} \${NIXL_INSTALL_DIR} -Ddisable_gds_backend=true"
+          test_cmd='.gitlab/test_plugins.sh $NIXL_INSTALL_DIR'
+          ./aws_test.sh "$test_cmd" 2>&1 | tee test_output.log
+
       - name: Cleanup AWS resources
         if: always()
         run: |
+          # Cleanup AWS Batch job if it was created
+          if [ -f ./contrib/aws-efa/test_output.log ]; then
+            JOB_ID=$(grep 'JOB_ID=' ./contrib/aws-efa/test_output.log | head -n1 | cut -d= -f2)
+            if [ -n "$JOB_ID" ]; then
+              echo "Terminating AWS Batch job: $JOB_ID"
+              aws batch terminate-job --job-id "$JOB_ID" --reason 'Terminated by GitHub Actions' || true
+            fi
+          fi
+
           # Delete S3 bucket
           aws s3 rb s3://${AWS_DEFAULT_BUCKET} --force
-
